kind: Pod
apiVersion: v1
metadata:
  name: mongo

spec:

  volumes:
    - name: mongo-data
      # TODO: Complete volume declaration here

  containers:
    - name: mongo
      image: "mongo:7"
      ports:
        - containerPort: 27017
          name: "mongo"
      volumeMounts:
        - mountPath: "/data/db"
          name: mongo-data
