apiVersion: v1
kind: Pod
metadata:
  name: prod-pod
  labels:
    app: mongo

spec:

  containers:
    - name: prod
      image: "mongo:7"

  tolerations:
    - key: node-type
      operator: Equal
      value: prod
      effect: NoSchedule