---
apiVersion: v1
kind: Pod
metadata:
  name: mongo
  labels:
    env: development

spec:
  containers:
    - name: mongo
      image: mongo:5
      ports:
          - containerPort: 27017
            name: mongo
            protocol: TCP
...
