version: '3'
services:
  article-svc:
    image: "alphayax/microservice-demo-article-service:latest"
    environment: []
    ports:
      - "8080:8080"
    depends_on:
      - "mongo"
  mongo:
    image: "mongo"
