version: '3'
services:

  nginx:
    image: nginx
    volumes:
      - "./nginx:/etc/nginx/conf.d"
    ports:
      - "8080:80"

  frontend-admin:
    image: "alphayax/microservice-demo-frontend-admin:latest"
    depends_on:
      - "article-svc"
    # TODO [1]: Frontend configuration (specify backend location)
    #volumes:

  article-svc:
    image: "alphayax/microservice-demo-article-service:latest"
    environment:
      MONGODB_URI: "mongodb://mongo:27017"
    depends_on:
      - "mongo"

  mongo:
    image: "mongo:4"
    # TODO [2]: Add persistence
    #volumes:
