version: '3'

services:
  webservice:
    build:
      context: ../webservice-test
    networks:
      - web
    expose:
      - "8080"
    labels:
      - "traefik.backend=webservice"
      - "traefik.frontend.rule=Host:webservice.docker.localhost"
  front:
    build:
      context: ../front-test
    networks:
      - web
    expose:
      - "3000"
    labels:
      - "traefik.backend=front"
      - "traefik.frontend.rule=Host:front.docker.localhost"

networks:
  web:
    external:
      name: traefik_webgateway
