version: '3'
services:
  db:
    image: mariadb:5
    volumes:
      ##
      # Add volume mount to persist MariaDB data (répertoire /var/lib/mysql)
      ##
    restart: always
    environment:
      ##
      # Add environment variables for the MariaDB credentials
      ##
  dbadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    environment:
      ##
      # Add environment variables for the MariaDB+PHPMyAdmin
      ##
    depends_on:
      ##
      # Add the dependency
      ##

  wordpress:
    image: wordpress:latest
    depends_on:
      ##
      # Add the dependency
      ##
    ports:
      - "8000:80"
    restart: always
    environment:
      ##
      # Add environment variables for the MariaDB credentials
      ##
