version: '3'
services:

  # Article Service
  article-svc:
    image: "alphayax/microservice-demo-article-service:latest"
    environment:
      MONGODB_URI: "mongodb://mongo:27017"
    depends_on:
      - "mongo"

  # MongoDb
  mongo:
    image: "mongo"

  # Frontend Admin
  frontend-admin:
    image: "alphayax/microservice-demo-frontend-admin:latest"
    ports:
      - "8080:80"
    depends_on:
      - "article-svc"
