apiVersion: v1
kind: Service
metadata:
  name: my-cip-service
spec:
  type: ClusterIP
  selector:
    app: metrics
    department: ingeneering
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080